### ISSUE TITLE
Publish first newsletter

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/newsletter#1]
Just creating an issue for us to track and discuss the first newsletter...

**Comment by katiewhite360** [comment]
Newsletter Strategy: 

I. GitHub for Collaboration/Input
- jupyter/newsletter repo will be made public so that anyone can add content or ideas 
- follows the general structure outlined in the newsletter template (see [docker](https://blog.docker.com/docker-weekly-archives/) for examle) 

II. Curation 
- Important/relevant content will be pulled and incorporated into a concise newsleter 
- Newsletter will be posted on the blog, mailing list, and sent via Mailchimp to subscribers on Tuesdays every other week at 8:30 am

**Comment by Carreau** [comment]
> Newsletter will be posted on the blog, mailing list, and sent via Mailchimp to subscribers on Tuesdays every other week at 8:30 am

Which timezone ?

**Comment by katiewhite360** [comment]
Pst

On Friday, February 19, 2016, Matthias Bussonnier notifications@github.com
wrote:

> Newsletter will be posted on the blog, mailing list, and sent via
> Mailchimp to subscribers on Tuesdays every other week at 8:30 am
> 
> Which timezone ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/1#issuecomment-186427406.

## 

_Katie White_
VP of Marketing - Cal Poly Entrepreneurs
Business Admin. Intern - Project Jupyter
Cal Poly Business
Cell: 801.910.6717

**Comment by Carreau** [comment]
What do you think of pushing the publication on Tuesday afternoon/evening, then we can add the link to the last 2 dev meeting which are on Youtube and are usually on Tuesday from 10 to 11 PST ?

**Comment by takluyver** [comment]
Do we want to include IPython stuff in the newsletter, or more strictly Jupyter? I could describe the prompt_toolkit stuff.

**Comment by Carreau** [comment]
> Do we want to include IPython stuff in the newsletter, or more strictly Jupyter? I could describe the prompt_toolkit stuff.

Yes IMHO, IPython is a demo of think you can do in Jupyter, and what we do with Prompt toolkit will go into jupyter_console as well right ?

**Comment by takluyver** [comment]
The jupyter_console thing is a good point. The terminal interface of IPython is sort of orthogonal to Jupyter, except that the two projects are closely related.

**Comment by Ruv7** [comment]
I like the idea of having a link to the meeting recordings, what is the processing time for getting the video uploaded to Youtube? Who does this normally? Perhaps we can include recordings from the previous two weeks and not the one from that day. Ideally I would want to get into our readers inbox before 10am. 

I know some email systems have automated schedules we can create for different "send" times based on the time zone of the record. So that all time zones get the email at 9am in their region. This feature would be dependent of course on collecting that data (which I dont believe we have now) so I will work to figure out what our options are.

**Comment by Ruv7** [comment]
Also I like the idea of having a Developer's Corner or Technical updates section. We will look to you to decide what to highlight and feature...

**Comment by Carreau** [comment]
> what is the processing time for getting the video uploaded to Youtube?

less than 1h30, the recorder (Me of F.) get a link to download a few minutes after recording. (I got the link at 11:14 today) and the human is definitively the limitting factor.
I'm currently reuploading to Youtube, I set the date, the title (append the date) and click on a few option (like allow community to edit close captioning). You get the actual link imediately (Initialized empty Git repository in https://youtu.be/T8hnyTvxiE0 for today). It usually take 5 minutes for YT to put the video online.

We can make the 2 previous recording, I just feel like missing this by a few hours is sad. Or we could move on wednesday morning ?

**Comment by Ruv7** [comment]
True. Yes I would be ok with that. I would want to seek the opinions of Brian/Katie to see if they agree. I think in Marketing circles there is much discussion about the ideal time/day and I don't see that there is a consensus. As long as Monday and Friday are eliminated then I'm on board.

**Comment by takluyver** [comment]
> I know some email systems have automated schedules we can create for different "send" times based on the time zone of the record. So that all time zones get the email at 9am in their region.
1. I don't think that's worth the bother.
2. I don't want to make this like a marketing campaign - that sort of thing tends to annoy geeks anyway. It's a service we'll provide for people who are interested. If it comes when they're too busy look at it, they can save it for later or ignore it as they choose. We don't want or need clever tricks to take advantage of people's attention.
3. We're a globally communicating community, and trying to do something at the same clock time in each time zone means doing it at different actual times. If you send it out at 9am in California (5pm in the UK), people on the internet in the evening here will see responses to the newsletter before they actually get the newsletter the next morning.
