### ISSUE TITLE
[TOPIC] Featured users/contributors 

### ISSUE THREAD

**Issue by katiewhite360** [jupyter/newsletter#21]
For this newsletter Ana was thinking Matthias and Cameron to be highlighted as the featured users/contributors - thoughts? 

Cameron's bio summary and picture are en route.

**Comment by Ruv7** [comment]
I think we can cycle through Jupyter's Core team on an ad hoc basis and take particular suggestions for someone being featured or highlighted just like we would any other story suggestion. Do you have contact info for everyone on the team? I can share if not. I would go ahead and gather some photos and bios in advance so that you can simply insert them as there is room in the newsletter. Perhaps make the request post the Dev Meeting next week. Many people are likely busy right now preparing to be out of the office for one week...

**Comment by katiewhite360** [comment]
Good idea, that'd take a lot of pressure off for future newsletters.
Can I start
this on Monday?

**Comment by Ruv7** [comment]
Yup, I would actually suggest waiting to ask people for photos/bios until April 3 (post the Dev Meeting). The only two you have to worry about gathering in time for the next newsletter would be Matthias and Cameron.

**Comment by Carreau** [comment]
### Matthias Bussonnier

Matthias is a French Physicist. He has been a core developer of IPython and Jupyter since 2012, and has been a PostDoc working full time on IPython & Jupyter at UC Berkeley. Matthias 

I'll update this comment later, you should have the ability to update it too. I'm bad at describing myself ingeneral .

**Comment by katiewhite360** [comment]
Could I get a picture?
Katie White VP of Marketing - Cal Poly Entrepreneurs Business Admin. Intern - Project Jupyter Cal Poly Business Cell: 801.910.6717

On Mon, Mar 28, 2016 at 10:04 AM, Matthias Bussonnier < notifications@github.com > wrote:
MATTHIAS BUSSONNIER
Matthias is a French Physicist. He has been a core developer of IPython and
Jupyter since 2012, and has been a PostDoc working full time on IPython &
Jupyter at UC Berkeley. Matthias

I'll update this comment later, you should have the ability to update it too.
I'm bad at describing myself ingeneral .

**Comment by katiewhite360** [comment]
Hey Matthias - could I get one sentence on what you are working on right now?

**Comment by Ruv7** [comment]
@katiewhite360 - is there where you're keeping track of featured contributor submissions you have on deck? If not should we close out the issue? Not sure if this continues to be useful otherwise.

**Comment by katiewhite360** [comment]
They are in my email. Yes feel free to close it out.
Katie White Vice President - Cal Poly Entrepreneurs Business Administration - Project Jupyter Cal Poly Business Cell: 801.910.6717

On Tue, May 31, 2016 2:08 PM, Ana Ruvalcaba notifications@github.com wrote:
@katiewhite360 - is there where you're keeping track of featured contributor submissions you
have on deck? If not should we close out the issue? Not sure if this continues
to be useful otherwise.
