### ISSUE TITLE
Using issues for posting topic suggestions?

### ISSUE THREAD

**Issue by fperez** [jupyter/newsletter#30]
@Carreau has already three issues (#4, #16 and #18) that suggest topics to include in future newsletters.  That seems like a good way to proceed to me, for example today I thought [the Lego robot post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/4GDoEqFM768/RPEFEju2AAAJ) would make for a nice little blurb.

@Ruv7, @katiewhite360, others: should we proceed with this plan, that in general whenever anyone thinks of a good topic to post about, they can ping you all by simply opening an issue here, which we can label with "Topic" (I can make that label if we like the plan)? That way, you can easily filter topic proposals by just looking at open issues with that label, and work through them quickly...

**Comment by Ruv7** [comment]
Yes, that works. Note though the most efficient thing for technical topics is to have ideas contributed in the following format: 

Headline + Two to Four Sentence Description +  A link to more info + Photo/Diagram where available

Sometimes I can pick out the most interesting thing in technical articles but other times it may as well be in Portuguese. Because I speak Spanish I will understand part of it but will struggle with what would be important to the Jupyter community about the articles you send my way with no further guidance. :)

**Comment by willingc** [comment]
@fperez @Ruv7 @katiewhite360 @Carreau I've added an ISSUE_TEMPLATE.md to this repo that will remind submitters to include Ana's requested information about a story. When someone clicks "New Issue" in this repo, the template will display the desired submission information.

I've also gone back and tagged Matthias' story suggestions with the prefix [TOPIC]. I  added a suggestion to include Lorena Barba's keynote at PyCon 2016 to a June newsletter issue #32.

cc/ @ellisonbg
