### ISSUE TITLE
Collaboration instruction likely unclear. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/newsletter#38]
Hi, 

I did made some changes during the review stage on the newsletter, that were saved, as I could still see them across days when revisiting the page. 

Though they seem to not have made it to the final version. 

Mainly a description on the image, plus a few link. 

also there is now this "Newsletter Jupyter ........... June15th" header which was not there before, is not the right resolution and is duplicate content for the header.

So did I miss something ?

**Comment by willingc** [comment]
@katiewhite360 @Ruv7 This caused me a bit of confusion as well.

Take a look at the shared draft and private notes feature. This may be preferable to allowing individual reviewers to edit directly. https://help.medium.com/hc/en-us/articles/215274128-Collaboration-tools

**Comment by katiewhite360** [comment]
@Carreau your revisions were all valid - I moved the image description into the paragraph below because that image became the issue header (which isn't formatted with a caption). The reason for duplicating the header is so that the issue number and date show up in the thumbnail/preview version. 

@willingc I don't think those capabilities work with the letter format, but I will double check. Sharing and editing would definitely be nice.
